# Generated by Django 3.2.5 on 2021-08-29 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_category', models.CharField(max_length=255)),
                ('agent_institution', models.CharField(max_length=255)),
                ('agent_pricing', models.FloatField(default=0)),
                ('product_name', models.CharField(max_length=255)),
                ('vrn', models.CharField(blank=True, max_length=10)),
                ('transaction_id', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=255)),
                ('receipt_number', models.CharField(max_length=255)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_commission', models.FloatField(default=0)),
                ('transaction_status', models.CharField(blank=True, max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('commission_month', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Sales',
                'verbose_name_plural': 'Agent Sales',
            },
        ),
    ]
