# Generated by Django 4.0.1 on 2022-04-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsale',
            name='customer_IDnumber',
            field=models.CharField(default='424234', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentsale',
            name='customer_cell',
            field=models.CharField(default='12313', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentsale',
            name='customer_email',
            field=models.CharField(default='fadfadfaf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentsale',
            name='customer_name',
            field=models.CharField(default='afafaf', max_length=255),
            preserve_default=False,
        ),
    ]
