# Generated by Django 3.2.5 on 2021-08-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('CategoryA', 'CategoryA'), ('CategoryB', 'CategoryB'), ('CategoryC', 'CategoryC'), ('CategoryD', 'CategoryD'), ('CategoryE', 'CategoryE'), ('CategoryF', 'CategoryF'), ('CategoryG', 'CategoryG')], max_length=255)),
                ('price', models.FloatField(default=0, help_text='Enter Percentage as Decimals')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
