# Generated by Django 3.2.5 on 2021-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_insuranceapiurlconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapiurlconfig',
            name='api_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insuranceapiurlconfig',
            name='key_identifier',
            field=models.CharField(choices=[('ThirdPartyQoute', 'ThirdPartyQoute'), ('ThirdPartyPayment', 'ThirdPartyPayment'), ('ThirdPartyPolicy', 'ThirdPartyPolicy'), ('ZinaraQuote', 'ZinaraQuote'), ('RadioQuote', 'RadioQuote'), ('LicensingPayment', 'LicensingPayment'), ('LicensingPolicy', 'LicensingPolicy'), ('ThirdPartyZinaraQoute', 'ThirdPartyZinaraQoute'), ('ThirdPartyZinaraPayment', 'ThirdPartyZinaraPayment'), ('ThirdPartyZinaraPolicy', 'ThirdPartyZinaraPolicy'), ('CheckVehicle', 'CheckVehicle')], help_text='Select The Relevant Api Category Based On URL', max_length=255, unique=True),
        ),
    ]
