# Generated by Django 4.0.1 on 2022-04-21 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0003_auto_20210829_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyScheduleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PolicySchedulePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IceCashEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(choices=[('3RDPARTYQUOTE', '3RDPARTYQUOTE'), ('3RDPARTYUPDATE', '3RDPARTYUPDATE'), ('3RDPARTYPOLICY', '3RDPARTYPOLICY'), ('COMPREHENSIVEQUOTE', 'COMPREHENSIVEQUOTE'), ('REVERSAL', 'REVERSAL'), ('LICENSINGQUOTE', 'LICENSINGQUOTE'), ('LICENSINGUPDATE', 'LICENSINGUPDATE'), ('LICENSINGPOLICY', 'LICENSINGPOLICY'), ('COMBINEDQUOTE', 'COMBINEDQUOTE'), ('COMBINEDUPDATE', 'COMBINEDUPDATE'), ('COMBINEDPOLICY', 'COMBINEDPOLICY')], max_length=255)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=False)),
                ('env_status', models.CharField(choices=[('LIVE', 'LIVE'), ('TEST', 'TEST')], max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
