# Generated by Django 3.2.5 on 2021-08-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='agent_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.agencypricing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='approved_colors',
            field=models.CharField(blank=True, help_text='Upload Hex Colors Only', max_length=30),
        ),
        migrations.AlterField(
            model_name='institution',
            name='approved_logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
