# Generated by Django 3.2.5 on 2021-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210802_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='industry',
            field=models.CharField(choices=[('Consulting', 'Consulting'), ('Electronic Payments', 'Electronic Payments'), ('Banking', 'Banking'), ('Funeral Services', 'Funeral Services'), ('Micro Finance', 'Micro Finance'), ('Tertiary', 'Tertiary')], max_length=255),
        ),
    ]
