# Generated by Django 3.2.5 on 2021-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_institution_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
