# Generated by Django 3.2.5 on 2021-08-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_institution_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='manager',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
